network:
  ethernets:
    eno8:
      dhcp4: false
      dhcp6: false
  bridges:
    br10:
      interfaces: [ eno8 ]
      addresses: [192.168.71.56/24]
      gateway4: 192.168.8.1
      mtu: 1500
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no
  version: 2
